### ISSUE TITLE
runtime error: slice bounds out of range [:-2]

### ISSUE THREAD

**Issue by m-barthelemy** [TremoloSecurity/kube-oidc-proxy#17]
We recently updated our old Jetstack kube-oidc-proxy to the latest release here.

We're unable to get it to work; looks like all successful requests throw the following:
```
http: panic serving 10.43.1.158:26762: runtime error: slice bounds out of range [:-2]
goroutine 23835 [running]:
net/http.(*conn).serve.func1()
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/server.go:1801 +0xb9
panic({0x1c5efa0, 0xc0003d3848})
	/opt/hostedtoolcache/go/1.17.0/x64/src/runtime/panic.go:1047 +0x266
github.com/jetstack/kube-oidc-proxy/pkg/proxy.(*Proxy).logSuccessfulRequest(0x1, 0xc0008fbf00, {0x2053ec8, 0xc0005956c0}, {0x0, 0x0})
	/home/runner/work/kube-oidc-proxy/kube-oidc-proxy/pkg/proxy/proxy.go:261 +0x5e5
github.com/jetstack/kube-oidc-proxy/pkg/proxy.(*Proxy).RoundTrip(0xc0006c8180, 0xc0008fbf00)
	/home/runner/work/kube-oidc-proxy/kube-oidc-proxy/pkg/proxy/proxy.go:220 +0x245
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc0007349b0, {0x204c510, 0xc000018380}, 0xc0008fbe00)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/httputil/reverseproxy.go:298 +0x92a
k8s.io/apiserver/pkg/endpoints/filters.WithRequestInfo.func1({0x204c510, 0xc000018380}, 0xc0008fbd00)
	/home/runner/go/pkg/mod/k8s.io/apiserver@v0.23.0/pkg/endpoints/filters/requestinfo.go:39 +0x316
net/http.HandlerFunc.ServeHTTP(0xc0008fbc00, {0x204c510, 0xc000018380}, 0x0)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/server.go:2046 +0x2f
github.com/jetstack/kube-oidc-proxy/pkg/proxy.(*Proxy).withImpersonateRequest.func1({0x204c510, 0xc000018380}, 0x1e7a601)
	/home/runner/work/kube-oidc-proxy/kube-oidc-proxy/pkg/proxy/handlers.go:215 +0x996
net/http.HandlerFunc.ServeHTTP(0x2053918, {0x204c510, 0xc000018380}, 0x1e7a618)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/server.go:2046 +0x2f
github.com/jetstack/kube-oidc-proxy/pkg/proxy.(*Proxy).withAuthenticateRequest.func1({0x204c510, 0xc000018380}, 0x10000c000189d40)
	/home/runner/work/kube-oidc-proxy/kube-oidc-proxy/pkg/proxy/handlers.go:58 +0x382
net/http.HandlerFunc.ServeHTTP(0xc000739969, {0x204c510, 0xc000018380}, 0x46696e)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/server.go:2046 +0x2f
net/http.serverHandler.ServeHTTP({0xc0004fc630}, {0x204c510, 0xc000018380}, 0xc0003a1800)
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc000357e00, {0x2053918, 0xc000768450})
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/opt/hostedtoolcache/go/1.17.0/x64/src/net/http/server.go:3033 +0x4e8
```

Looking at the code pointed by the stacktrace:
https://github.com/TremoloSecurity/kube-oidc-proxy/blob/master/pkg/proxy/proxy.go#L259-L264

If the `X-Forwarded-For` header is present, it will try to do slightly fancy stuff to remove the IP of the proxy.
My guess is that if `X-Forwarded-For` only contains 1 value, then `X-Forwarded-For` can be equal to `remoteAddr`.
The code ends up doing something like:
 `xFwdFor = xFwdFor[0 : len("1.1.1.1")-(len("1.1.1.1")+2)]` => `xFwdFor = xFwdFor[0 : 7 - (7+2)]` => `xFwdFor = xFwdFor[0 :-2]`

**Comment by mlbiam** [comment]
What's your ingress controller?

**Comment by m-barthelemy** [comment]
Our kube-oidc-proxy is behind an AWS Network Load Balancer in TLS mode (which makes the issue slightly odd, NLBs are TCP level load balancers, and as such, don't even add X-Forwarded-For headers).

That being said, this might be a generic issue if my theory that `X-Forwarded-For` can be strictly equal to `remoteAddr` makes sense.

**Comment by m-barthelemy** [comment]
I was able to manually reproduce the issue by setting an empty `X-Forwarded-for` header, and calling the `kube-oidc-proxy` pod directly (zero intermediate or ingress besides k8s port forwarding):

```
curl -XPOST -k -v -H "Authorization: bearer <insert_valid_token_here>" -H "X-Forwarded-For:" https://kube-oidc-proxy-endpoint
```

Also happens when **not sending** any `X-Forwarded-For` header:
```
curl -XPOST -k -v -H "Authorization: bearer <insert_valid_token_here>" https://kube-oidc-proxy-endpoint
```

So it looks like kube-oidc-proxy is _expecting_ to be provided this header, and https://github.com/TremoloSecurity/kube-oidc-proxy/blob/9687f2dbecdd33f1b944fcfc7e36e82ef3873254/pkg/proxy/proxy.go#L256 contains something that makes https://github.com/TremoloSecurity/kube-oidc-proxy/blob/9687f2dbecdd33f1b944fcfc7e36e82ef3873254/pkg/proxy/proxy.go#L259 to be evaluated as `true`.

**Comment by mlbiam** [comment]
Thanks for the verification @m-barthelemy.  I'm refactoring that code now so we can better isolate the use case and test.  Hoping to get you a container to test today.

**Comment by mlbiam** [comment]
Set your image to `docker.io/tremolosecurity/betas:kube-oidc-proxy` and try again.  That should fix this

**Comment by m-barthelemy** [comment]
> kube-oidc-proxy

Confirmed, working beautifully so far.
Thanks a lot for the quick fix!

Will there be a new official release with the fix soon?

**Comment by mlbiam** [comment]
> Confirmed, working beautifully so far.

Excellent

> Will there be a new official release with the fix soon?

probably next week.  having an issue with the end2end testing framework that doesn't appear to have anything to do with the actual proxy we're working out now.

**Comment by m-barthelemy** [comment]
Hi, apologies for the ping.
I know time is most likely the key here, but do you think a new release with the fix could be made soon?

**Comment by mlbiam** [comment]
@m-barthelemy just rolled out.  `docker.io/tremolosecurity/kube-oidc-proxy:latest` now has this fix (along with some much needed version bumps)

**Comment by m-barthelemy** [comment]
We have successfully upgraded all our old Jetstack kube-oidc-proxy instances to this new Tremolosecurity release.
Thanks again for the fix!
