### ISSUE TITLE
General deployment helm charts and deployment yaml files references the jetstack image

### ISSUE THREAD

**Issue by TonniNTF** [TremoloSecurity/kube-oidc-proxy#21]
Both helm charts and yaml files needs updating to use the new image.
Might need other updates as well.

**Comment by mlbiam** [comment]
Tremolo Security is only actively maintaining and testing the helm charts for OpenUnison.  All of the other charts, terraform scripts, and manifests in this repo that were created by JetStack are outside of our focus.  We are happy to accept community contributions on these (and any other deployment mechanism) that the community would like kept in this repo.  

For reference, here's the template we're actively testing with - https://github.com/OpenUnison/helm-charts/blob/master/orchestra/templates/infrastructure/jetstack.yaml
