### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by rabalaGit** [TremoloSecurity/kube-oidc-proxy#23]
Deployed in my EKS cluster with AWS NLB. Using an AWS ACM certificate for the NLB. 
I am getting below error in my kube-oidc-proxy pod logs
________
I0805 15:15:41.263776       1 dynamic_serving_content.go:111] Loaded a new cert/key pair for "serving-cert::/etc/oidc/tls/crt.pem::/etc/oidc/tls/key.pem"
I0805 15:15:41.264632       1 tlsconfig.go:200] loaded serving cert ["serving-cert::/etc/oidc/tls/crt.pem::/etc/oidc/tls/key.pem"]: "kube-oidc-proxy.keycloak.svc.cluster.local" [serving,client] issuer="kube-oidc-proxy-ca" (2022-08-05 15:15:38 +0000 UTC to 2023-08-05 15:15:38 +0000 UTC (now=2022-08-05 15:15:41.264615102 +0000 UTC))
I0805 15:15:41.264650       1 secure_serving.go:178] Serving securely on [::]:443
I0805 15:15:41.264713       1 dynamic_serving_content.go:130] Starting serving-cert::/etc/oidc/tls/crt.pem::/etc/oidc/tls/key.pem
I0805 15:15:41.264730       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0805 15:16:00.243431       1 probe.go:69] OIDC provider initialized, proxy ready
I0805 15:16:00.243462       1 probe.go:70] OIDC provider initialized, readiness check returned error: oidc: verify token: oidc: expected audience "my oidc client name -- redacted" got []

_________________
Please help me in solving this issue

**Comment by mlbiam** [comment]
`error: oidc: verify token: oidc: expected audience "my oidc client name -- redacted" got []`

This means that your `aud` claim in your JWT is not set.  Make sure the `aud` is being set to `my oidc client name -- redacted`

**Comment by rabalaGit** [comment]
Thanks for your response.
I verified and confirm that "aud" is being set to my "oidc client name -- redacted"
