### ISSUE TITLE
Help with exposing kube-oidc-proxy behind WAF

### ISSUE THREAD

**Issue by rucciva** [TremoloSecurity/kube-oidc-proxy#36]
Hi, thanks for continue maintaining this. 

I'm planning to expose it behind some cloud provider's WAF, but i have a bit of problem.
Currently, any non streaming operation such as get list of pods, is working. Also proxy, port-forward, or even using kubevpn to have vpn access inside the kubernetes is fine. 

But weirdly kubectl logs *-f* is not working, it won't stream the logs. Also if i'm using k9s, the interface won't update if there is a state change, such as pod is terminating etc. 

Do you have any ideas on possible reason why this is happening?. I'm not sure it is the problem with kube-oidc-proxy but i'm not sure what to tell to the operator of WAF regarding this problem.

Thanks

**Comment by mlbiam** [comment]
sorry for the delayed response.  Ive seen issues like this behind certain load balancers.  Azure's WAPv1 comes to mind.  What WAF are you using?  If `kubectl logs -f` isn't working, does just getting the logs at once work?

**Comment by rucciva** [comment]
Hi, Thanks for the response.

Its huaweicloud WAF and yes, getting the logs at once work.

**Comment by mlbiam** [comment]
I'd check what the underlying tech is. I know the issue with azure wapv1 is it's built on IIS. But it's not a kube-oidc-proxy issue
