### ISSUE TITLE
Case sensitive issues

### ISSUE THREAD

**Issue by saiharshitachava** [TremoloSecurity/kube-oidc-proxy#38]
we noticed the original kube-oidc project was case sensitive with reference to user names..

i.e A user is authenticated via the provider and the flow goes to authorization and oidc is reading the user ID lets say test@EXAMPLE.COM from provider and if user logs in with test@example.com authorization of kube api fails 

Any help on this is highly appreciated

**Comment by mlbiam** [comment]
Can you please provide a specific example of what the issue is?  Pleas eprovide specific API calls, JWT claims, and corresponding RBAC rules with your expectations and actual results.

**Comment by mlbiam** [comment]
closing due to lack of response
