### ISSUE TITLE
error: [issuer.audiences: Required value: at least one issuer.audiencs not contain any valid RSA or ECDSA certificates]

### ISSUE THREAD

**Issue by saiharshitach** [TremoloSecurity/kube-oidc-proxy#58]
We suddenly started seeing this issue in few clusters where we have kube-oidc and the pod goes into crashloopbackoff. I have the same cert working in other clusters so Im not sure if its something with the setup but any leads on what could go wrong here

error: [issuer.audiences: Required value: at least one issuer.audiencs not contain any valid RSA or ECDSA certificates]

**Comment by mlbiam** [comment]
Can you please provide the image and tag, as well as the specific output from the container?

**Comment by saiharshitach** [comment]
sure 
we are using version 1.0.6 and the log (verbose also gives the same nothing new)

I0919 11:30:57.630690       1 dynamic_serving_content.go:116] "Loaded a new cert/key pair" name="serving-cert::/etc/oidc/tls/crt.pem::/etc/oidc/tls/key.pem"
Error: [issuer.audiences: Required value: at least one issuer.audiences is required, issuer.certificateAuthority: Invalid value: "<omitted>": data does not contain any valid RSA or ECDSA certificates]
Usage:
  kube-oidc-proxy [flags]

Kube-OIDC-Proxy flags:

      --disable-impersonation                    (Alpha) Disable the rded as is.
      --extra-user-header-client-ip              (Alpha) If enabled, ent-IP: <REMOTE_ADDR>' where <REMOTE_ADDR> will contain the remote ad
      --extra-user-headers stringToStringSlice   (Alpha) A list of keimpersonated request. A single key can hold multiple values. (default
      --flush-interval duration                  Specifies the interve means to flush immediately after each write. Streaming requests suc
  -P, --readiness-probe-port int                 Port to expose readi
      --token-passthrough                        (Alpha) Requests witthe Token Review endpoint. If successful, the request is sent on as i
      --token-passthrough-audiences strings      (Alpha) List of the resource server will verify that non OIDC tokens are intended for at ce will default to the audience of the Kubernetes apiserver. Only use

OIDC flags:

      --oidc-ca-file string                   The OpenID server's cere the host's root CA set will be used
      --oidc-client-id string                 The client ID for the O
      --oidc-groups-claim string              If provided, the name opected to be a string or array of strings.
      --oidc-groups-prefix string             If provided, all groupsstrategies.
      --oidc-issuer-url string                The URL of the OpenID i
      --oidc-required-claim mapStringString   A key=value pair that desent in the ID Token with a matching value. Repeat this flag to spec
      --oidc-signing-algs strings             Comma-separated list ofn this list will be rejected. Values are defined by RFC 7518 https://
      --oidc-username-claim string            The OpenID claim to useed to be unique and immutable (default "sub")
      --oidc-username-prefix string           If provided, all userna 'email' are prefixed by the issuer URL to avoid clashes. To skip any

Secure Serving flags:

      --bind-address ip                        The IP address on whicable by the rest of the cluster, and by CLI/web clients. If blank or ll be used. (default 0.0.0.0)
      --cert-dir string                        The directory where thed, this flag will be ignored. (default "/var/run/kubernetes")
      --disable-http2-serving                  If true, HTTP2 serving
      --http2-max-streams-per-connection int   The limit that the serero means to use golang's default.
      --permit-address-sharing                 If true, SO_REUSEADDR 0.0 and specific IPs in parallel, and it avoids waiting for the kerne
      --permit-port-sharing                    If true, SO_REUSEPORT n the same address and port. [default=false]
      --secure-port int                        The port on which to s0. (default 6443)
      --tls-cert-file string                   File containing the det). If HTTPS serving is enabled, and --tls-cert-file and --tls-privatthe public address and saved to the directory specified by --cert-dir
      --tls-cipher-suites strings              Comma-separated list oused.
                                               Preferred values: TLS_HE_ECDSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA25 TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305, TLS_ECDHE_ECDSA_WITH_CHACHA2_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_ECDHE_RSA_WITH_AA20_POLY1305_SHA256.
                                               Insecure values: TLS_ESA_WITH_3DES_EDE_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_BC_SHA, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_GCM_SHARC4_128_SHA.
      --tls-min-version string                 Minimum TLS version su
      --tls-private-key-file string            File containing the de
      --tls-sni-cert-key namedCertKey          A pair of x509 certifins which are fully qualified domain names, possibly with prefixed wilbe used if the apiserver has visibility to the IP address requested bextracted. Non-wildcard matches trump over wildcard matches, explicituse the --tls-sni-cert-key multiple times. Examples: "example.crt,exa

Audit flags:

      --audit-log-batch-buffer-size int             The size of the bult 10000)
      --audit-log-batch-max-size int                The maximum size
      --audit-log-batch-max-wait duration           The amount of timsed in batch mode.
      --audit-log-batch-throttle-burst int          Maximum number ofed in batch mode.
      --audit-log-batch-throttle-enable             Whether batching
      --audit-log-batch-throttle-qps float32        Maximum average n
      --audit-log-compress                          If set, the rotat
      --audit-log-format string                     Format of saved auctured json format. Known formats are legacy,json. (default "json")
      --audit-log-maxage int                        The maximum numbeilename.
      --audit-log-maxbackup int                     The maximum numbetriction on the number of files.
      --audit-log-maxsize int                       The maximum size
      --audit-log-mode string                       Strategy for send. Batch causes the backend to buffer and write events asynchronously.
      --audit-log-path string                       If set, all reque
      --audit-log-truncate-enabled                  Whether event and
      --audit-log-truncate-max-batch-size int       Maximum size of tndreds of bytes greater. If a batch exceeds this limit, it is split i
      --audit-log-truncate-max-event-size int       Maximum size of t than this number, first request and response are removed, and if thi
      --audit-log-version string                    API group and ver)
      --audit-policy-file string                    Path to the file
      --audit-webhook-batch-buffer-size int         The size of the bult 10000)
      --audit-webhook-batch-max-size int            The maximum size
      --audit-webhook-batch-max-wait duration       The amount of timsed in batch mode. (default 30s)
      --audit-webhook-batch-throttle-burst int      Maximum number ofed in batch mode. (default 15)
      --audit-webhook-batch-throttle-enable         Whether batching
      --audit-webhook-batch-throttle-qps float32    Maximum average n
      --audit-webhook-config-file string            Path to a kubecon
      --audit-webhook-initial-backoff duration      The amount of tim
      --audit-webhook-mode string                   Strategy for send. Batch causes the backend to buffer and write events asynchronously.
      --audit-webhook-truncate-enabled              Whether event and
      --audit-webhook-truncate-max-batch-size int   Maximum size of tndreds of bytes greater. If a batch exceeds this limit, it is split i
      --audit-webhook-truncate-max-event-size int   Maximum size of t than this number, first request and response are removed, and if thi
      --audit-webhook-version string                API group and ver/v1")

Client flags:

      --as-uid string                  UID to impersonate for the ope
      --certificate-authority string   Path to a cert file for the ce
      --client-certificate string      Path to a client certificate f
      --client-key string              Path to a client key file for
      --cluster string                 The name of the kubeconfig clu
      --context string                 The name of the kubeconfig con
      --disable-compression            If true, opt-out of response c
      --insecure-skip-tls-verify       If true, the server's certificure
      --kubeconfig string              Path to the kubeconfig file to
  -n, --namespace string               If present, the namespace scop
      --request-timeout string         The length of time to wait befponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't time
  -s, --server string                  The address and port of the Ku
      --tls-server-name string         Server name to use for server erver is used
      --token string                   Bearer token for authenticatio
      --user string                    The name of the kubeconfig use

Misc flags:

  -h, --help                           help for kube-oidc-proxy
      --log-flush-frequency duration   Maximum number of seconds betw
  -v, --v Level                        number for the log level verbo
      --version                        Print version information and
      --vmodule moduleSpec             comma-separated list of pattert)

error: [issuer.audiences: Required value: at least one issuer.audiencs not contain any valid RSA or ECDSA certificates]

**Comment by mlbiam** [comment]
That's odd.  can you please provide the full URL for the image you're using?

**Comment by hobayoba** [comment]
+1
image: `tremolosecurity/kube-oidc-proxy:1.0.6`

**Comment by mlbiam** [comment]
That is strange.  Try the github image instead: `ghcr.io/tremolosecurity/kube-oidc-proxy:1.0.6-e24311`

**Comment by mlbiam** [comment]
wait i think I see what happened.  try `tremolosecurity/kube-oidc-proxy:1.0.6-f1a6c3` (or the github equiv)

**Comment by saiharshitach** [comment]
This works @mlbiam 

Was there any change pushed to 1.0.6 which broke this

**Comment by mlbiam** [comment]
I see what happened.  Our dev pipeline got misconfigured to push to the tremolosecurity dockerhub.  When we started updates for 1.0.7 this was an issue in a build we fixed.  The impacted image was 1.0.6-8a33e3 which only existed in dockerhub, it didn't exist in github's registry.  The issue has been fixed, the offending tag deleted and 1.0.6 now points to 1.0.6-f1a6c3.
